### ISSUE TITLE
Error create ticket 

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#70]
![Screenshot 2024-06-08 061524](https://github.com/ralphkb/sentinel-tickets/assets/133818503/73d25f00-1787-4693-a8fa-67b66415cf4b)

**Comment by ralphkb** [comment]
Hey, please review your configuration for possible mistakes in the ticket category permissions. This error likely means issues within your ticket category permissions configuration.

This part to be precise:
```YAML
    permissions: # The permissions of the category, make sure to never add the same permission to both the allow and deny arrays of either open or close properties
      ticketCreator:
        open:
          allow: ["ViewChannel", "SendMessages", "EmbedLinks", "AttachFiles", "ReadMessageHistory"] # The bot will allow those permissions to the ticket creator in an open ticket
          deny: [] # The bot will deny those permissions from the ticket creator in an open ticket
        close:
          allow: [] # The bot will allow those permissions to the ticket creator in a closed ticket
          deny: ["SendMessages"] # The bot will deny those permissions from the ticket creator in a closed ticket
      supportRoles:
        open:
          allow: ["ViewChannel", "SendMessages", "EmbedLinks", "AttachFiles", "ReadMessageHistory"]
          deny: []
        close:
          allow: []
          deny: ["SendMessages"]
      addedRoles:
        open:
          allow: ["ViewChannel", "SendMessages", "EmbedLinks", "AttachFiles", "ReadMessageHistory"]
          deny: []
        close:
          allow: []
          deny: ["SendMessages"]
      addedUsers:
        open:
          allow: ["ViewChannel", "SendMessages", "EmbedLinks", "AttachFiles", "ReadMessageHistory"]
          deny: []
        close:
          allow: []
          deny: ["SendMessages"]
```

Depending if you're on the latest commit or not, you may not have the addedRoles & addedUsers options but then you can just update to get them.
If you are certain they're correct, then you likely have outdated files that you need to update.
