### ISSUE TITLE
Auto closed does not lock SendMessage for Client

### ISSUE THREAD

**Issue by mrc4tt** [ralphkb/sentinel-tickets#83]
**Describe the bug**
Roles can still send messages even if the bot has shut down the ticket.
Then it should no longer be possible for people with specific roles to be unable to send messages.
Unfortunately, they can only do it when the bot has autoclosed the ticket.

**To Reproduce**
Steps to reproduce the behaviour, for example:
1. Type something random text
2. Wait until the ticket is autoclosed (automatically by bot)
3. Login on the backup Discord Account, and I can still send message
4. Bugged

**Expected behaviour**

**Screenshots**
![image](https://github.com/user-attachments/assets/fb968220-1bbe-44e1-ae24-3d29e483eaca)

![image](https://github.com/user-attachments/assets/8fdbb5bc-a3f4-4ee0-8c05-1f338fc8c7b1)

**Logs**
There are no logs of the errors (not on PM2)

**Additional context**
It is tested with `/close` which works perfectly. So the problem here is the autoclose does not apply permission changes.
![image](https://github.com/user-attachments/assets/8e5bee45-66eb-4a51-a43c-725a70e0cda7)

**Comment by mrc4tt** [comment]
@ralphkb

**Comment by ralphkb** [comment]
Hey, I just tested and it works fine so double check your configuration and test again. The autoclose function surely handles both the ticket creator and the roles so that's not a bug in the code but in your setup of the bot.

This is the code that handles the roles permissions and it takes the permissions based on your configuration: https://github.com/ralphkb/sentinel-tickets/blob/main/utils/ticketAutoClose.js#L227

Ensure that `supportRoles` has `SendMessages` in the close deny array, basically similar to the default values in `config.yml.example`:
```YAML
    permissions: # The permissions of the category, make sure to never add the same permission to both the allow and deny arrays of either open or close properties
      ticketCreator:
        open:
          allow: ["ViewChannel", "SendMessages", "EmbedLinks", "AttachFiles", "ReadMessageHistory"] # The bot will allow those permissions to the ticket creator in an open ticket
          deny: [] # The bot will deny those permissions from the ticket creator in an open ticket
        close:
          allow: [] # The bot will allow those permissions to the ticket creator in a closed ticket
          deny: ["SendMessages"] # The bot will deny those permissions from the ticket creator in a closed ticket
      supportRoles:
        open:
          allow: ["ViewChannel", "SendMessages", "EmbedLinks", "AttachFiles", "ReadMessageHistory"]
          deny: []
        close:
          allow: []
          deny: ["SendMessages"]
```
